import React, { useState, useEffect } from 'react';
import {
  Wrench,
  Calendar,
  ClipboardCheck,
  BarChart3,
  Plus,
  Search,
  Filter,
  CheckCircle2,
  Clock,
  AlertTriangle,
  AlertCircle,
  Play,
  Check,
  SkipForward,
  Trash2,
  Edit2,
  RotateCw,
  Eye,
  Building,
  Layers,
  ShieldCheck,
  Sparkles,
  ArrowRight,
  TrendingUp,
  FileSpreadsheet,
} from 'lucide-react';
import {
  PMPlan,
  PMSchedule,
  PMWorkOrder,
  PMComplianceMetrics,
  Machine,
  Branch,
  Department,
  Employee,
  PMChecklistTaskItem,
} from '../types.ts';
import { useApp } from '../context/AppContext.tsx';
import { fetchApi } from '../lib/api.ts';
import { PMChecklistExecutionModal } from './PMChecklistExecutionModal.tsx';

export const PreventiveMaintenanceView: React.FC = () => {
  const { currentRole, currentBranchId, currentDepartmentId, branches, departments, showToast } = useApp();

  const isEditor = currentRole === 'admin' || currentRole === 'super_manager';

  // Sub-tabs
  type PMTab = 'work_orders' | 'schedules' | 'master_plans' | 'compliance_reports';
  const [activeSubTab, setActiveSubTab] = useState<PMTab>('work_orders');

  // Core Data
  const [workOrders, setWorkOrders] = useState<PMWorkOrder[]>([]);
  const [schedules, setSchedules] = useState<PMSchedule[]>([]);
  const [plans, setPlans] = useState<PMPlan[]>([]);
  const [machines, setMachines] = useState<Machine[]>([]);
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [complianceReport, setComplianceReport] = useState<PMComplianceMetrics | null>(null);
  const [loading, setLoading] = useState<boolean>(true);

  // Filters
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [priorityFilter, setPriorityFilter] = useState<string>('all');
  const [selectedMachineFilter, setSelectedMachineFilter] = useState<string>('all');
  const [dueRangeFilter, setDueRangeFilter] = useState<string>('all');

  // Modals
  const [selectedWorkOrderForExecution, setSelectedWorkOrderForExecution] = useState<PMWorkOrder | null>(null);
  const [isExecutionModalOpen, setIsExecutionModalOpen] = useState<boolean>(false);

  // Skip Modal
  const [skipTargetWO, setSkipTargetWO] = useState<PMWorkOrder | null>(null);
  const [skipReason, setSkipReason] = useState<string>('');
  const [skipping, setSkipping] = useState<boolean>(false);

  // Plan Create / Edit Modal
  const [isPlanModalOpen, setIsPlanModalOpen] = useState<boolean>(false);
  const [editingPlan, setEditingPlan] = useState<PMPlan | null>(null);
  const [planForm, setPlanForm] = useState({
    code: '',
    title: '',
    description: '',
    category: 'Mechanical & Calibration',
    frequencyType: 'monthly',
    frequencyInterval: 1,
    estimatedDurationMinutes: 60,
    priority: 'medium',
    machineCategory: '',
    safetyNotes: '',
    tasks: [] as PMChecklistTaskItem[],
    parts: [] as { itemName: string; quantity: number; uom: string }[],
  });

  // Schedule Assign Modal
  const [isScheduleModalOpen, setIsScheduleModalOpen] = useState<boolean>(false);
  const [editingSchedule, setEditingSchedule] = useState<PMSchedule | null>(null);
  const [scheduleForm, setScheduleForm] = useState({
    planId: '',
    machineId: '',
    assignedEmployeeId: '',
    scheduleType: 'fixed_calendar',
    frequencyType: 'monthly',
    frequencyInterval: 1,
    startDate: new Date().toISOString().split('T')[0],
    nextDueDate: new Date().toISOString().split('T')[0],
    autoGenerateDaysInAdvance: 7,
    notes: '',
  });

  // Load all PM domain data
  const loadPMData = async () => {
    try {
      setLoading(true);
      const branchParam = (currentRole === 'admin' || currentRole === 'super_manager') ? '' : `branchId=${currentBranchId}`;

      const [woData, schedData, planData, mchData, empData, repData] = await Promise.all([
        fetchApi<PMWorkOrder[]>(`/api/pm/work-orders?${branchParam}`),
        fetchApi<PMSchedule[]>(`/api/pm/schedules?${branchParam}`),
        fetchApi<PMPlan[]>('/api/pm/plans'),
        fetchApi<Machine[]>(`/api/machines?branchId=${currentBranchId}`),
        fetchApi<Employee[]>(`/api/employees?branchId=${currentBranchId}`),
        fetchApi<PMComplianceMetrics>(`/api/pm/compliance-report?${branchParam}`),
      ]);

      setWorkOrders(woData || []);
      setSchedules(schedData || []);
      setPlans(planData || []);
      setMachines(mchData || []);
      setEmployees(empData || []);
      setComplianceReport(repData || null);
    } catch (err: any) {
      console.error('Failed to load PM suite data:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPMData();
  }, [currentBranchId, currentRole]);

  // Handle Start WO
  const handleStartWorkOrder = async (wo: PMWorkOrder) => {
    try {
      await fetchApi(`/api/pm/work-orders/${wo.id}/start`, { method: 'POST' });
      showToast(`Work order ${wo.workOrderNumber} started!`, 'success');
      loadPMData();
    } catch (err: any) {
      showToast(err.message || 'Failed to start work order', 'error');
    }
  };

  // Handle Skip WO
  const handleConfirmSkip = async () => {
    if (!skipTargetWO || !skipReason.trim()) {
      showToast('Please provide a reason to skip this scheduled maintenance.', 'error');
      return;
    }
    try {
      setSkipping(true);
      await fetchApi(`/api/pm/work-orders/${skipTargetWO.id}/skip`, {
        method: 'POST',
        body: JSON.stringify({ skippedReason: skipReason }),
      });
      showToast(`Work order ${skipTargetWO.workOrderNumber} marked as skipped.`, 'info');
      setSkipTargetWO(null);
      setSkipReason('');
      loadPMData();
    } catch (err: any) {
      showToast(err.message || 'Failed to skip work order', 'error');
    } finally {
      setSkipping(false);
    }
  };

  // Trigger Auto-generation of Due Work Orders
  const handleGenerateDueWorkOrders = async () => {
    try {
      const res = await fetchApi<{ success: boolean; createdCount: number; message: string }>('/api/pm/work-orders/generate-due', {
        method: 'POST',
      });
      showToast(res.message || `Created ${res.createdCount} due work orders`, 'success');
      loadPMData();
    } catch (err: any) {
      showToast(err.message || 'Failed to generate due orders', 'error');
    }
  };

  // Plan Management
  const handleOpenCreatePlan = () => {
    setEditingPlan(null);
    setPlanForm({
      code: `PM-${Date.now().toString().slice(-4)}`,
      title: '',
      description: '',
      category: 'Mechanical & Calibration',
      frequencyType: 'monthly',
      frequencyInterval: 1,
      estimatedDurationMinutes: 60,
      priority: 'medium',
      machineCategory: '',
      safetyNotes: '',
      tasks: [
        {
          id: 'task-1',
          order: 1,
          task: 'Lubricate all guide ways and linear bearings',
          instruction: 'Verify oil pressure and inspect way wipers for chips.',
          type: 'pass_fail',
          isRequired: true,
        },
      ],
      parts: [],
    });
    setIsPlanModalOpen(true);
  };

  const handleOpenEditPlan = (p: PMPlan) => {
    setEditingPlan(p);
    setPlanForm({
      code: p.code,
      title: p.title,
      description: p.description || '',
      category: p.category,
      frequencyType: p.frequencyType,
      frequencyInterval: p.frequencyInterval || 1,
      estimatedDurationMinutes: p.estimatedDurationMinutes || 60,
      priority: p.priority || 'medium',
      machineCategory: p.machineCategory || '',
      safetyNotes: p.safetyNotes || '',
      tasks: (p.checklistTemplate as PMChecklistTaskItem[]) || [],
      parts: (p.requiredPartsTemplate as any[]) || [],
    });
    setIsPlanModalOpen(true);
  };

  const handleSavePlan = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!planForm.title.trim()) {
      showToast('Plan title is required', 'error');
      return;
    }

    try {
      const payload = {
        code: planForm.code,
        title: planForm.title,
        description: planForm.description,
        category: planForm.category,
        frequencyType: planForm.frequencyType,
        frequencyInterval: planForm.frequencyInterval,
        estimatedDurationMinutes: planForm.estimatedDurationMinutes,
        priority: planForm.priority,
        machineCategory: planForm.machineCategory,
        safetyNotes: planForm.safetyNotes,
        checklistTemplate: planForm.tasks,
        requiredPartsTemplate: planForm.parts,
      };

      if (editingPlan) {
        await fetchApi(`/api/pm/plans/${editingPlan.id}`, {
          method: 'PUT',
          body: JSON.stringify(payload),
        });
        showToast('PM Master Plan updated successfully!', 'success');
      } else {
        await fetchApi('/api/pm/plans', {
          method: 'POST',
          body: JSON.stringify(payload),
        });
        showToast('PM Master Plan created successfully!', 'success');
      }

      setIsPlanModalOpen(false);
      loadPMData();
    } catch (err: any) {
      showToast(err.message || 'Failed to save PM plan', 'error');
    }
  };

  const handleDeletePlan = async (p: PMPlan) => {
    if (!confirm(`Are you sure you want to delete Master Plan "${p.title}" (${p.code})? This will also remove associated recurring schedules.`)) {
      return;
    }
    try {
      await fetchApi(`/api/pm/plans/${p.id}`, { method: 'DELETE' });
      showToast('Master Plan deleted', 'success');
      loadPMData();
    } catch (err: any) {
      showToast(err.message || 'Failed to delete plan', 'error');
    }
  };

  // Schedule Management
  const handleOpenAssignSchedule = () => {
    setEditingSchedule(null);
    setScheduleForm({
      planId: plans[0]?.id ? plans[0].id.toString() : '',
      machineId: machines[0]?.id ? machines[0].id.toString() : '',
      assignedEmployeeId: '',
      scheduleType: 'fixed_calendar',
      frequencyType: 'monthly',
      frequencyInterval: 1,
      startDate: new Date().toISOString().split('T')[0],
      nextDueDate: new Date().toISOString().split('T')[0],
      autoGenerateDaysInAdvance: 7,
      notes: '',
    });
    setIsScheduleModalOpen(true);
  };

  const handleSaveSchedule = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!scheduleForm.planId || !scheduleForm.machineId) {
      showToast('Please select both a Master Plan and a Machine', 'error');
      return;
    }

    try {
      if (editingSchedule) {
        await fetchApi(`/api/pm/schedules/${editingSchedule.id}`, {
          method: 'PUT',
          body: JSON.stringify(scheduleForm),
        });
        showToast('Recurring Schedule updated successfully!', 'success');
      } else {
        await fetchApi('/api/pm/schedules', {
          method: 'POST',
          body: JSON.stringify(scheduleForm),
        });
        showToast('Recurring PM Schedule assigned to machine!', 'success');
      }
      setIsScheduleModalOpen(false);
      loadPMData();
    } catch (err: any) {
      showToast(err.message || 'Failed to save schedule', 'error');
    }
  };

  const handleDeleteSchedule = async (sched: PMSchedule) => {
    if (!confirm('Are you sure you want to remove this recurring PM schedule?')) return;
    try {
      await fetchApi(`/api/pm/schedules/${sched.id}`, { method: 'DELETE' });
      showToast('PM Schedule removed', 'success');
      loadPMData();
    } catch (err: any) {
      showToast(err.message || 'Failed to delete schedule', 'error');
    }
  };

  // Filtered Work Orders
  const filteredWorkOrders = workOrders.filter((wo) => {
    const q = searchQuery.toLowerCase();
    const matchQuery =
      !searchQuery ||
      wo.workOrderNumber.toLowerCase().includes(q) ||
      wo.title.toLowerCase().includes(q) ||
      (wo.machine?.name && wo.machine.name.toLowerCase().includes(q)) ||
      (wo.machine?.machineCode && wo.machine.machineCode.toLowerCase().includes(q)) ||
      (wo.plan?.title && wo.plan.title.toLowerCase().includes(q));

    const matchStatus =
      statusFilter === 'all' ||
      (statusFilter === 'overdue' ? wo.isOverdue : wo.status === statusFilter);

    const matchPriority = priorityFilter === 'all' || wo.priority === priorityFilter;
    const matchMachine = selectedMachineFilter === 'all' || wo.machineId === parseInt(selectedMachineFilter);

    const todayStr = new Date().toISOString().split('T')[0];
    let matchDue = true;
    if (dueRangeFilter === 'today') {
      matchDue = wo.dueDate === todayStr;
    } else if (dueRangeFilter === 'overdue') {
      matchDue = Boolean(wo.isOverdue);
    } else if (dueRangeFilter === 'next7days') {
      const in7Days = new Date(Date.now() + 86400000 * 7).toISOString().split('T')[0];
      matchDue = wo.dueDate >= todayStr && wo.dueDate <= in7Days;
    }

    return matchQuery && matchStatus && matchPriority && matchMachine && matchDue;
  });

  const overdueWOCount = workOrders.filter((wo) => wo.isOverdue).length;
  const inProgressCount = workOrders.filter((wo) => wo.status === 'in_progress').length;
  const completedCount = workOrders.filter((wo) => wo.status === 'completed').length;

  return (
    <div className="space-y-6">
      {/* Top Banner / Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-6 rounded-2xl border border-slate-200/80 shadow-xs">
        <div>
          <div className="flex items-center gap-2.5">
            <div className="w-10 h-10 rounded-xl bg-blue-600/10 border border-blue-200 flex items-center justify-center text-blue-600 shadow-xs">
              <Wrench className="w-5 h-5" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-slate-900 tracking-tight">
                Preventive Maintenance System
              </h1>
              <p className="text-xs text-slate-500 mt-0.5">
                Machine servicing schedules, dynamic parameter checklists, part consumption & compliance audits
              </p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2.5 shrink-0">
          <button
            onClick={handleGenerateDueWorkOrders}
            title="Scan active schedules and generate pending work orders"
            className="px-3.5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold rounded-xl transition flex items-center gap-2 cursor-pointer border border-slate-300 shadow-xs"
          >
            <RotateCw className="w-3.5 h-3.5" />
            Auto-Sync Due PMs
          </button>

          {isEditor && (
            <>
              <button
                onClick={handleOpenAssignSchedule}
                className="px-3.5 py-2 bg-slate-800 hover:bg-slate-900 text-white text-xs font-bold rounded-xl transition flex items-center gap-2 cursor-pointer shadow-xs"
              >
                <Calendar className="w-3.5 h-3.5" />
                + Assign Schedule
              </button>

              <button
                onClick={handleOpenCreatePlan}
                className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl transition flex items-center gap-2 cursor-pointer shadow-sm hover:shadow"
              >
                <Plus className="w-4 h-4" />
                New Master Plan
              </button>
            </>
          )}
        </div>
      </div>

      {/* Summary KPI Badges */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex items-center justify-between">
          <div>
            <span className="text-xs font-bold text-slate-400 block uppercase tracking-wider">
              Total Work Orders
            </span>
            <span className="text-2xl font-black text-slate-900 mt-1 block">
              {workOrders.length}
            </span>
          </div>
          <div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center text-slate-600 font-bold text-sm">
            <ClipboardCheck className="w-5 h-5" />
          </div>
        </div>

        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex items-center justify-between">
          <div>
            <span className="text-xs font-bold text-rose-500 block uppercase tracking-wider">
              Overdue Maintenance
            </span>
            <span className="text-2xl font-black text-rose-600 mt-1 block">
              {overdueWOCount}
            </span>
          </div>
          <div className="w-10 h-10 rounded-xl bg-rose-50 border border-rose-200 flex items-center justify-center text-rose-600 font-bold text-sm">
            <AlertTriangle className="w-5 h-5" />
          </div>
        </div>

        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex items-center justify-between">
          <div>
            <span className="text-xs font-bold text-blue-500 block uppercase tracking-wider">
              In Progress
            </span>
            <span className="text-2xl font-black text-blue-600 mt-1 block">
              {inProgressCount}
            </span>
          </div>
          <div className="w-10 h-10 rounded-xl bg-blue-50 border border-blue-200 flex items-center justify-center text-blue-600 font-bold text-sm">
            <Clock className="w-5 h-5" />
          </div>
        </div>

        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex items-center justify-between">
          <div>
            <span className="text-xs font-bold text-emerald-600 block uppercase tracking-wider">
              Compliance Rate
            </span>
            <span className="text-2xl font-black text-emerald-700 mt-1 block">
              {complianceReport ? `${complianceReport.complianceRatePercentage}%` : '100%'}
            </span>
          </div>
          <div className="w-10 h-10 rounded-xl bg-emerald-50 border border-emerald-200 flex items-center justify-center text-emerald-600 font-bold text-sm">
            <TrendingUp className="w-5 h-5" />
          </div>
        </div>
      </div>

      {/* Sub-Navigation Tabs */}
      <div className="flex border-b border-slate-200 space-x-1">
        <button
          onClick={() => setActiveSubTab('work_orders')}
          className={`px-4 py-2.5 text-xs font-bold transition-all border-b-2 flex items-center gap-2 cursor-pointer ${
            activeSubTab === 'work_orders'
              ? 'border-blue-600 text-blue-600'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          <ClipboardCheck className="w-4 h-4" />
          Work Orders Queue ({workOrders.length})
          {overdueWOCount > 0 && (
            <span className="bg-rose-500 text-white text-[10px] px-1.5 py-0.5 rounded-full font-bold">
              {overdueWOCount}
            </span>
          )}
        </button>

        <button
          onClick={() => setActiveSubTab('schedules')}
          className={`px-4 py-2.5 text-xs font-bold transition-all border-b-2 flex items-center gap-2 cursor-pointer ${
            activeSubTab === 'schedules'
              ? 'border-blue-600 text-blue-600'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          <Calendar className="w-4 h-4" />
          Recurring Schedules ({schedules.length})
        </button>

        <button
          onClick={() => setActiveSubTab('master_plans')}
          className={`px-4 py-2.5 text-xs font-bold transition-all border-b-2 flex items-center gap-2 cursor-pointer ${
            activeSubTab === 'master_plans'
              ? 'border-blue-600 text-blue-600'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          <Layers className="w-4 h-4" />
          Master Plans & Checklists ({plans.length})
        </button>

        <button
          onClick={() => setActiveSubTab('compliance_reports')}
          className={`px-4 py-2.5 text-xs font-bold transition-all border-b-2 flex items-center gap-2 cursor-pointer ${
            activeSubTab === 'compliance_reports'
              ? 'border-blue-600 text-blue-600'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          <BarChart3 className="w-4 h-4" />
          Compliance & Reliability Audits
        </button>
      </div>

      {/* ========================================================================= */}
      {/* 1. WORK ORDERS QUEUE TAB */}
      {/* ========================================================================= */}
      {activeSubTab === 'work_orders' && (
        <div className="space-y-4">
          {/* Filters Bar */}
          <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex flex-wrap items-center justify-between gap-3">
            <div className="flex-1 min-w-[240px] relative">
              <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
              <input
                type="text"
                placeholder="Search work order #, machine code, task title..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-9 pr-3 py-1.5 text-xs border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 bg-slate-50/50"
              />
            </div>

            <div className="flex flex-wrap items-center gap-2.5 text-xs">
              <select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="px-2.5 py-1.5 border border-slate-300 rounded-lg bg-white font-medium text-slate-700 focus:outline-none cursor-pointer"
              >
                <option value="all">All Statuses</option>
                <option value="scheduled">Scheduled</option>
                <option value="in_progress">In Progress</option>
                <option value="completed">Completed</option>
                <option value="skipped">Skipped</option>
                <option value="overdue">🔴 Overdue Only</option>
              </select>

              <select
                value={dueRangeFilter}
                onChange={(e) => setDueRangeFilter(e.target.value)}
                className="px-2.5 py-1.5 border border-slate-300 rounded-lg bg-white font-medium text-slate-700 focus:outline-none cursor-pointer"
              >
                <option value="all">Any Due Date</option>
                <option value="today">Due Today</option>
                <option value="next7days">Due Next 7 Days</option>
                <option value="overdue">Overdue</option>
              </select>

              <select
                value={priorityFilter}
                onChange={(e) => setPriorityFilter(e.target.value)}
                className="px-2.5 py-1.5 border border-slate-300 rounded-lg bg-white font-medium text-slate-700 focus:outline-none cursor-pointer"
              >
                <option value="all">All Priorities</option>
                <option value="critical">Critical</option>
                <option value="high">High</option>
                <option value="medium">Medium</option>
                <option value="low">Low</option>
              </select>

              <select
                value={selectedMachineFilter}
                onChange={(e) => setSelectedMachineFilter(e.target.value)}
                className="px-2.5 py-1.5 border border-slate-300 rounded-lg bg-white font-medium text-slate-700 focus:outline-none cursor-pointer"
              >
                <option value="all">All Machines</option>
                {machines.map((m) => (
                  <option key={m.id} value={m.id}>
                    {m.name} ({m.machineCode})
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* Work Orders List */}
          {loading ? (
            <div className="text-center py-12 bg-white rounded-xl border border-slate-200 text-slate-400 text-xs font-semibold">
              Loading Preventive Maintenance queue...
            </div>
          ) : filteredWorkOrders.length === 0 ? (
            <div className="text-center py-16 bg-white rounded-xl border border-slate-200">
              <ClipboardCheck className="w-12 h-12 text-slate-300 mx-auto mb-3" />
              <p className="text-slate-800 font-bold text-sm">No maintenance work orders found</p>
              <p className="text-slate-400 text-xs mt-1">Adjust filters or assign a recurring schedule to generate orders.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 gap-3">
              {filteredWorkOrders.map((wo) => {
                const isOverdue = wo.isOverdue;
                const isCompleted = wo.status === 'completed';
                const isInProgress = wo.status === 'in_progress';
                const isSkipped = wo.status === 'skipped';

                return (
                  <div
                    key={wo.id}
                    className={`bg-white rounded-xl border p-4.5 shadow-xs transition-all hover:shadow-md ${
                      isOverdue
                        ? 'border-rose-300 bg-rose-50/20'
                        : isInProgress
                        ? 'border-blue-300 bg-blue-50/20'
                        : isCompleted
                        ? 'border-emerald-200 bg-emerald-50/10'
                        : 'border-slate-200 hover:border-slate-300'
                    }`}
                  >
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                      {/* Left Details */}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap mb-1.5">
                          <span className="font-mono text-xs font-bold text-slate-900 bg-slate-100 px-2 py-0.5 rounded border border-slate-200">
                            {wo.workOrderNumber}
                          </span>

                          <span
                            className={`text-[10px] px-2 py-0.5 rounded-full font-bold uppercase tracking-wider ${
                              wo.priority === 'critical'
                                ? 'bg-rose-100 text-rose-800 border border-rose-200'
                                : wo.priority === 'high'
                                ? 'bg-amber-100 text-amber-800 border border-amber-200'
                                : 'bg-slate-100 text-slate-700'
                            }`}
                          >
                            {wo.priority} Priority
                          </span>

                          <span
                            className={`text-[10px] px-2 py-0.5 rounded-full font-bold uppercase tracking-wider ${
                              isCompleted
                                ? 'bg-emerald-100 text-emerald-800 border border-emerald-200'
                                : isOverdue
                                ? 'bg-rose-600 text-white animate-pulse'
                                : isInProgress
                                ? 'bg-blue-600 text-white'
                                : isSkipped
                                ? 'bg-slate-200 text-slate-700'
                                : 'bg-slate-100 text-slate-600 border border-slate-200'
                            }`}
                          >
                            {isOverdue ? 'OVERDUE' : wo.status.replace('_', ' ')}
                          </span>

                          {wo.plan?.category && (
                            <span className="text-slate-400 text-xs">• {wo.plan.category}</span>
                          )}
                        </div>

                        <h3 className="text-sm font-bold text-slate-900 truncate">
                          {wo.title}
                        </h3>

                        <div className="flex items-center gap-4 mt-2 text-xs text-slate-500 flex-wrap">
                          <span className="flex items-center gap-1 font-semibold text-slate-700">
                            <Wrench className="w-3.5 h-3.5 text-slate-400" />
                            Machine: {wo.machine?.name} ({wo.machine?.machineCode})
                          </span>

                          <span className="flex items-center gap-1">
                            <Building className="w-3.5 h-3.5 text-slate-400" />
                            {wo.branch?.name} / {wo.department?.name}
                          </span>

                          <span className="flex items-center gap-1 font-mono font-semibold">
                            <Calendar className="w-3.5 h-3.5 text-slate-400" />
                            Due: <strong className={isOverdue ? 'text-rose-600' : 'text-slate-800'}>{wo.dueDate}</strong>
                          </span>

                          {wo.assignedEmployee && (
                            <span className="flex items-center gap-1 text-slate-600">
                              <ShieldCheck className="w-3.5 h-3.5 text-blue-500" />
                              Assigned: {wo.assignedEmployee.name}
                            </span>
                          )}

                          {isCompleted && wo.completedByName && (
                            <span className="flex items-center gap-1 text-emerald-700 font-medium">
                              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
                              Signed: {wo.completedByName}
                            </span>
                          )}
                        </div>

                        {/* Completed Summary / Condition if completed */}
                        {isCompleted && (
                          <div className="mt-2.5 text-xs bg-emerald-50/60 p-2 rounded-lg border border-emerald-200 flex items-center gap-3 text-emerald-900">
                            <span className="font-semibold">
                              Health Condition: <span className="capitalize font-bold">{wo.overallCondition}</span>
                            </span>
                            {wo.timeSpentMinutes && (
                              <span>• Duration: {wo.timeSpentMinutes} mins</span>
                            )}
                            {wo.summaryNotes && (
                              <span className="text-slate-600 truncate max-w-md">• Notes: {wo.summaryNotes}</span>
                            )}
                          </div>
                        )}

                        {isSkipped && wo.skippedReason && (
                          <div className="mt-2 text-xs bg-slate-100 p-2 rounded-lg text-slate-600 italic">
                            Skipped reason: {wo.skippedReason}
                          </div>
                        )}
                      </div>

                      {/* Right Action Buttons */}
                      <div className="flex items-center gap-2 shrink-0">
                        {(!isCompleted && !isSkipped) && (
                          <>
                            {wo.status === 'scheduled' && (
                              <button
                                onClick={() => handleStartWorkOrder(wo)}
                                title="Start Work Order execution"
                                className="px-3 py-1.5 bg-blue-50 hover:bg-blue-100 text-blue-700 text-xs font-bold rounded-lg border border-blue-200 transition cursor-pointer flex items-center gap-1"
                              >
                                <Play className="w-3 h-3" /> Start PM
                              </button>
                            )}

                            <button
                              onClick={() => {
                                setSelectedWorkOrderForExecution(wo);
                                setIsExecutionModalOpen(true);
                              }}
                              className="px-3.5 py-1.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-lg transition shadow-xs cursor-pointer flex items-center gap-1.5"
                            >
                              <ClipboardCheck className="w-3.5 h-3.5" /> Execute & Sign
                            </button>

                            <button
                              onClick={() => setSkipTargetWO(wo)}
                              title="Skip this cycle with justification"
                              className="px-2.5 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-600 text-xs font-semibold rounded-lg transition cursor-pointer"
                            >
                              <SkipForward className="w-3.5 h-3.5" />
                            </button>
                          </>
                        )}

                        {isCompleted && (
                          <button
                            onClick={() => {
                              setSelectedWorkOrderForExecution(wo);
                              setIsExecutionModalOpen(true);
                            }}
                            className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold rounded-lg transition cursor-pointer flex items-center gap-1"
                          >
                            <Eye className="w-3.5 h-3.5" /> View Log
                          </button>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {/* ========================================================================= */}
      {/* 2. RECURRING SCHEDULES TAB */}
      {/* ========================================================================= */}
      {activeSubTab === 'schedules' && (
        <div className="space-y-4">
          <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex items-center justify-between">
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <Calendar className="w-4 h-4 text-blue-600" />
              Machine Recurring PM Frequency Rules
            </h2>
            {isEditor && (
              <button
                onClick={handleOpenAssignSchedule}
                className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-lg transition shadow-xs flex items-center gap-1.5 cursor-pointer"
              >
                <Plus className="w-3.5 h-3.5" /> Assign Schedule
              </button>
            )}
          </div>

          <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-50 border-b border-slate-200 text-slate-500 font-bold uppercase tracking-wider text-[10px]">
                <tr>
                  <th className="px-4 py-3">Machine / Asset</th>
                  <th className="px-4 py-3">PM Master Plan</th>
                  <th className="px-4 py-3">Frequency Cycle</th>
                  <th className="px-4 py-3">Next Due Date</th>
                  <th className="px-4 py-3">Assigned Tech</th>
                  <th className="px-4 py-3">Status</th>
                  {isEditor && <th className="px-4 py-3 text-right">Actions</th>}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 font-medium">
                {schedules.map((sched) => {
                  const isOverdue = sched.isOverdue;
                  return (
                    <tr key={sched.id} className="hover:bg-slate-50/70">
                      <td className="px-4 py-3">
                        <div className="font-bold text-slate-900">{sched.machine?.name}</div>
                        <div className="text-[11px] text-slate-400">{sched.machine?.machineCode} • {sched.branch?.name}</div>
                      </td>
                      <td className="px-4 py-3">
                        <div className="font-bold text-slate-800">{sched.plan?.title}</div>
                        <div className="text-[11px] text-slate-400 font-mono">{sched.plan?.code} ({sched.plan?.category})</div>
                      </td>
                      <td className="px-4 py-3">
                        <span className="capitalize font-semibold text-slate-700">
                          {sched.frequencyInterval > 1 ? `Every ${sched.frequencyInterval} ` : ''}
                          {sched.frequencyType.replace('_', ' ')}
                        </span>
                        <div className="text-[10px] text-slate-400">
                          {sched.scheduleType === 'fixed_calendar' ? 'Fixed Calendar' : 'Rolling after completion'}
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <span className={`font-mono font-bold ${isOverdue ? 'text-rose-600 bg-rose-50 px-2 py-0.5 rounded border border-rose-200' : 'text-slate-800'}`}>
                          {sched.nextDueDate}
                        </span>
                        {sched.lastCompletedDate && (
                          <div className="text-[10px] text-slate-400">Last: {sched.lastCompletedDate}</div>
                        )}
                      </td>
                      <td className="px-4 py-3">
                        {sched.assignedEmployee ? (
                          <span className="text-slate-800 font-semibold">{sched.assignedEmployee.name}</span>
                        ) : (
                          <span className="text-slate-400 italic">Unassigned</span>
                        )}
                      </td>
                      <td className="px-4 py-3">
                        <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold uppercase ${
                          sched.status === 'active' ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-200 text-slate-600'
                        }`}>
                          {sched.status}
                        </span>
                      </td>
                      {isEditor && (
                        <td className="px-4 py-3 text-right">
                          <button
                            onClick={() => handleDeleteSchedule(sched)}
                            title="Remove Schedule"
                            className="p-1.5 text-slate-400 hover:text-rose-600 rounded hover:bg-rose-50 transition cursor-pointer"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </td>
                      )}
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* 3. MASTER PLANS & TEMPLATES TAB */}
      {/* ========================================================================= */}
      {activeSubTab === 'master_plans' && (
        <div className="space-y-4">
          <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex items-center justify-between">
            <div>
              <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                <Layers className="w-4 h-4 text-blue-600" />
                Preventive Maintenance Master Plan Templates
              </h2>
              <p className="text-xs text-slate-500 mt-0.5">
                Standardized checklist tasks, acceptable numeric parameter tolerances, and required replacement parts
              </p>
            </div>
            {isEditor && (
              <button
                onClick={handleOpenCreatePlan}
                className="px-3.5 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl transition shadow-xs flex items-center gap-1.5 cursor-pointer"
              >
                <Plus className="w-4 h-4" /> Create Master Plan
              </button>
            )}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {plans.map((plan) => {
              const tasks = (plan.checklistTemplate as PMChecklistTaskItem[]) || [];
              const parts = (plan.requiredPartsTemplate as any[]) || [];

              return (
                <div
                  key={plan.id}
                  className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs flex flex-col justify-between"
                >
                  <div>
                    <div className="flex items-center justify-between gap-2 mb-2">
                      <span className="text-xs font-mono font-bold bg-blue-50 text-blue-700 px-2 py-0.5 rounded border border-blue-200">
                        {plan.code}
                      </span>
                      <span className="text-[10px] uppercase font-bold text-slate-500 bg-slate-100 px-2 py-0.5 rounded">
                        {plan.frequencyType} • ~{plan.estimatedDurationMinutes || 60}m
                      </span>
                    </div>

                    <h3 className="text-sm font-bold text-slate-900 leading-snug">
                      {plan.title}
                    </h3>
                    {plan.description && (
                      <p className="text-xs text-slate-500 mt-1 line-clamp-2">
                        {plan.description}
                      </p>
                    )}

                    {/* Task summary */}
                    <div className="mt-3.5 pt-3 border-t border-slate-100 space-y-1.5">
                      <span className="text-[11px] font-bold text-slate-600 uppercase tracking-wider block">
                        Inspection Tasks ({tasks.length})
                      </span>
                      {tasks.slice(0, 3).map((t, idx) => (
                        <div key={idx} className="flex items-center gap-2 text-xs text-slate-700">
                          <Check className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                          <span className="truncate">{t.task}</span>
                          {t.type === 'numeric' && (
                            <span className="text-[10px] font-mono bg-slate-100 px-1.5 rounded text-slate-500">
                              {t.minValue} - {t.maxValue} {t.unit}
                            </span>
                          )}
                        </div>
                      ))}
                      {tasks.length > 3 && (
                        <span className="text-[11px] text-blue-600 font-semibold block">
                          +{tasks.length - 3} more checklist items...
                        </span>
                      )}
                    </div>

                    {/* Parts summary */}
                    {parts.length > 0 && (
                      <div className="mt-3 pt-2 border-t border-slate-100 text-xs text-slate-500">
                        <strong className="text-slate-700">Parts/Fluids:</strong>{' '}
                        {parts.map((p) => `${p.itemName} (${p.quantity} ${p.uom})`).join(', ')}
                      </div>
                    )}
                  </div>

                  {/* Actions */}
                  {isEditor && (
                    <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between">
                      <span className="text-[11px] text-slate-400 font-medium">
                        Used in {plan.schedulesCount || 0} active schedules
                      </span>
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => handleOpenEditPlan(plan)}
                          className="p-1.5 text-slate-500 hover:text-blue-600 rounded hover:bg-slate-100 transition cursor-pointer"
                          title="Edit Master Plan"
                        >
                          <Edit2 className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDeletePlan(plan)}
                          className="p-1.5 text-slate-400 hover:text-rose-600 rounded hover:bg-rose-50 transition cursor-pointer"
                          title="Delete Master Plan"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* 4. COMPLIANCE & RELIABILITY AUDITS TAB */}
      {/* ========================================================================= */}
      {activeSubTab === 'compliance_reports' && (
        <div className="space-y-6">
          {complianceReport ? (
            <>
              {/* Analytics Header Metrics */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs">
                  <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">
                    Total PM Compliance Rate
                  </span>
                  <div className="flex items-baseline gap-3 mt-2">
                    <span className="text-3xl font-black text-emerald-600">
                      {complianceReport.complianceRatePercentage}%
                    </span>
                    <span className="text-xs text-slate-500 font-medium">
                      ({complianceReport.completedCount} / {complianceReport.totalWorkOrders} Executed)
                    </span>
                  </div>
                  <div className="w-full bg-slate-100 h-2 rounded-full overflow-hidden mt-3">
                    <div
                      className="bg-emerald-500 h-full rounded-full transition-all duration-500"
                      style={{ width: `${complianceReport.complianceRatePercentage}%` }}
                    />
                  </div>
                </div>

                <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs">
                  <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">
                    On-Time Servicing Rate
                  </span>
                  <div className="flex items-baseline gap-3 mt-2">
                    <span className="text-3xl font-black text-blue-600">
                      {complianceReport.onTimeCompletionRatePercentage}%
                    </span>
                    <span className="text-xs text-slate-500 font-medium">
                      Within maintenance window
                    </span>
                  </div>
                  <div className="w-full bg-slate-100 h-2 rounded-full overflow-hidden mt-3">
                    <div
                      className="bg-blue-500 h-full rounded-full transition-all duration-500"
                      style={{ width: `${complianceReport.onTimeCompletionRatePercentage}%` }}
                    />
                  </div>
                </div>

                <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs">
                  <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">
                    Average Service Duration
                  </span>
                  <div className="flex items-baseline gap-2 mt-2">
                    <span className="text-3xl font-black text-slate-800">
                      {complianceReport.avgCompletionDurationMinutes}
                    </span>
                    <span className="text-xs text-slate-500 font-semibold">Minutes / Machine</span>
                  </div>
                  <p className="text-[11px] text-slate-400 mt-2">Based on logged technician timestamps</p>
                </div>
              </div>

              {/* Machine Health Distribution */}
              <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-xs">
                <h3 className="text-sm font-bold text-slate-900 mb-4 flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-blue-600" />
                  Machine Condition & Health Distribution
                </h3>
                <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
                  <div className="p-3 rounded-xl bg-emerald-50/70 border border-emerald-200 text-center">
                    <span className="text-[10px] font-bold text-emerald-800 uppercase tracking-wider block">Excellent</span>
                    <span className="text-xl font-black text-emerald-900 mt-1 block">
                      {complianceReport.conditionBreakdown?.excellent || 0}
                    </span>
                  </div>
                  <div className="p-3 rounded-xl bg-green-50/70 border border-green-200 text-center">
                    <span className="text-[10px] font-bold text-green-800 uppercase tracking-wider block">Good</span>
                    <span className="text-xl font-black text-green-900 mt-1 block">
                      {complianceReport.conditionBreakdown?.good || 0}
                    </span>
                  </div>
                  <div className="p-3 rounded-xl bg-amber-50/70 border border-amber-200 text-center">
                    <span className="text-[10px] font-bold text-amber-800 uppercase tracking-wider block">Fair (Monitor)</span>
                    <span className="text-xl font-black text-amber-900 mt-1 block">
                      {complianceReport.conditionBreakdown?.fair || 0}
                    </span>
                  </div>
                  <div className="p-3 rounded-xl bg-orange-50/70 border border-orange-200 text-center">
                    <span className="text-[10px] font-bold text-orange-800 uppercase tracking-wider block">Poor (Action)</span>
                    <span className="text-xl font-black text-orange-900 mt-1 block">
                      {complianceReport.conditionBreakdown?.poor || 0}
                    </span>
                  </div>
                  <div className="p-3 rounded-xl bg-rose-50/70 border border-rose-200 text-center">
                    <span className="text-[10px] font-bold text-rose-800 uppercase tracking-wider block">Critical (Offline)</span>
                    <span className="text-xl font-black text-rose-900 mt-1 block">
                      {complianceReport.conditionBreakdown?.critical || 0}
                    </span>
                  </div>
                </div>
              </div>

              {/* Maintenance by Category Table */}
              {complianceReport.categoryBreakdown && complianceReport.categoryBreakdown.length > 0 && (
                <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
                  <div className="px-5 py-3.5 bg-slate-50 border-b border-slate-200 font-bold text-xs text-slate-800 flex items-center justify-between">
                    <span>Maintenance Categories Execution Audit</span>
                  </div>
                  <table className="w-full text-left text-xs">
                    <thead className="bg-slate-50/50 border-b border-slate-200 text-slate-500 font-bold uppercase tracking-wider text-[10px]">
                      <tr>
                        <th className="px-4 py-2.5">Category</th>
                        <th className="px-4 py-2.5 text-center">Total Scheduled</th>
                        <th className="px-4 py-2.5 text-center">Completed</th>
                        <th className="px-4 py-2.5 text-right">Completion Rate</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 font-medium">
                      {complianceReport.categoryBreakdown.map((cat, i) => {
                        const pct = cat.total > 0 ? Math.round((cat.completed / cat.total) * 100) : 0;
                        return (
                          <tr key={i} className="hover:bg-slate-50">
                            <td className="px-4 py-2.5 font-bold text-slate-800">{cat.category}</td>
                            <td className="px-4 py-2.5 text-center font-mono text-slate-700">{cat.total}</td>
                            <td className="px-4 py-2.5 text-center font-mono text-emerald-700 font-bold">{cat.completed}</td>
                            <td className="px-4 py-2.5 text-right font-mono font-bold text-slate-800">{pct}%</td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              )}
            </>
          ) : (
            <div className="text-center py-12 bg-white rounded-xl border border-slate-200 text-slate-400 text-xs">
              Calculating reliability audit metrics...
            </div>
          )}
        </div>
      )}

      {/* ========================================================================= */}
      {/* MODAL 1: CHECKLIST EXECUTION MODAL */}
      {/* ========================================================================= */}
      <PMChecklistExecutionModal
        isOpen={isExecutionModalOpen}
        onClose={() => {
          setIsExecutionModalOpen(false);
          setSelectedWorkOrderForExecution(null);
        }}
        workOrder={selectedWorkOrderForExecution}
        onSuccess={loadPMData}
      />

      {/* ========================================================================= */}
      {/* MODAL 2: SKIP WORK ORDER REASON PROMPT */}
      {/* ========================================================================= */}
      {skipTargetWO && (
        <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl p-6 max-w-md w-full shadow-2xl border border-slate-200 animate-in fade-in zoom-in-95 duration-200">
            <div className="flex items-center gap-3 text-amber-600 mb-3">
              <AlertTriangle className="w-6 h-6" />
              <h3 className="text-sm font-bold text-slate-900">Skip Scheduled Maintenance</h3>
            </div>
            <p className="text-xs text-slate-600 leading-relaxed">
              Skipping <strong>{skipTargetWO.title}</strong> requires an explicit justification for regulatory compliance and audit logs. The next maintenance cycle will automatically be scheduled.
            </p>

            <div className="mt-4">
              <label className="text-xs font-bold text-slate-700 block mb-1.5">
                Mandatory Reason / Justification:
              </label>
              <textarea
                rows={3}
                value={skipReason}
                onChange={(e) => setSkipReason(e.target.value)}
                placeholder="e.g. Machine currently undergoing third-party retrofit; scheduled maintenance deferred with plant manager approval."
                className="w-full px-3 py-2 text-xs border border-slate-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-amber-500"
              />
            </div>

            <div className="flex items-center justify-end gap-2.5 mt-5">
              <button
                type="button"
                onClick={() => setSkipTargetWO(null)}
                className="px-3.5 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-100 rounded-lg cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleConfirmSkip}
                disabled={skipping || !skipReason.trim()}
                className="px-4 py-2 bg-amber-600 hover:bg-amber-700 text-white text-xs font-bold rounded-xl transition cursor-pointer disabled:opacity-50"
              >
                {skipping ? 'Recording...' : 'Confirm Skip Cycle'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* MODAL 3: MASTER PLAN BUILDER / EDITOR */}
      {/* ========================================================================= */}
      {isPlanModalOpen && (
        <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4 sm:p-6 overflow-y-auto">
          <div className="bg-white rounded-2xl shadow-2xl max-w-3xl w-full max-h-[92vh] flex flex-col overflow-hidden border border-slate-200">
            <div className="px-6 py-4.5 bg-slate-900 text-white flex items-center justify-between shrink-0">
              <h2 className="text-sm font-bold text-white flex items-center gap-2">
                <Layers className="w-4 h-4 text-blue-400" />
                {editingPlan ? `Edit Master Plan: ${editingPlan.code}` : 'Create PM Master Plan Template'}
              </h2>
              <button
                onClick={() => setIsPlanModalOpen(false)}
                className="text-slate-400 hover:text-white p-1 rounded-lg cursor-pointer"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleSavePlan} className="flex-1 overflow-y-auto p-6 space-y-5 text-xs">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div>
                  <label className="font-bold text-slate-700 block mb-1">Plan Code</label>
                  <input
                    type="text"
                    required
                    value={planForm.code}
                    onChange={(e) => setPlanForm({ ...planForm, code: e.target.value })}
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg font-mono font-bold focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>

                <div className="sm:col-span-2">
                  <label className="font-bold text-slate-700 block mb-1">Master Plan Title</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. CNC Spindle Geometric Calibration & Way Lubrication"
                    value={planForm.title}
                    onChange={(e) => setPlanForm({ ...planForm, title: e.target.value })}
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg font-semibold focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
                <div>
                  <label className="font-bold text-slate-700 block mb-1">Category</label>
                  <select
                    value={planForm.category}
                    onChange={(e) => setPlanForm({ ...planForm, category: e.target.value })}
                    className="w-full px-2.5 py-2 border border-slate-300 rounded-lg bg-white font-medium focus:outline-none"
                  >
                    <option value="Mechanical & Calibration">Mechanical & Calibration</option>
                    <option value="Hydraulic & Pressure">Hydraulic & Pressure</option>
                    <option value="Electrical & Sensors">Electrical & Sensors</option>
                    <option value="Optics & Thermal">Optics & Thermal</option>
                    <option value="Pneumatics & Cleanliness">Pneumatics & Cleanliness</option>
                    <option value="Safety & Interlocks">Safety & Interlocks</option>
                  </select>
                </div>

                <div>
                  <label className="font-bold text-slate-700 block mb-1">Default Frequency</label>
                  <select
                    value={planForm.frequencyType}
                    onChange={(e) => setPlanForm({ ...planForm, frequencyType: e.target.value })}
                    className="w-full px-2.5 py-2 border border-slate-300 rounded-lg bg-white font-medium focus:outline-none"
                  >
                    <option value="daily">Daily</option>
                    <option value="weekly">Weekly</option>
                    <option value="biweekly">Bi-Weekly</option>
                    <option value="monthly">Monthly</option>
                    <option value="quarterly">Quarterly</option>
                    <option value="semi_annually">Semi-Annually</option>
                    <option value="annually">Annually</option>
                  </select>
                </div>

                <div>
                  <label className="font-bold text-slate-700 block mb-1">Priority</label>
                  <select
                    value={planForm.priority}
                    onChange={(e) => setPlanForm({ ...planForm, priority: e.target.value })}
                    className="w-full px-2.5 py-2 border border-slate-300 rounded-lg bg-white font-medium focus:outline-none"
                  >
                    <option value="critical">Critical</option>
                    <option value="high">High</option>
                    <option value="medium">Medium</option>
                    <option value="low">Low</option>
                  </select>
                </div>

                <div>
                  <label className="font-bold text-slate-700 block mb-1">Est. Duration (Mins)</label>
                  <input
                    type="number"
                    min="5"
                    value={planForm.estimatedDurationMinutes}
                    onChange={(e) => setPlanForm({ ...planForm, estimatedDurationMinutes: parseInt(e.target.value) || 0 })}
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg font-mono font-bold focus:outline-none"
                  />
                </div>
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">Description / Purpose</label>
                <textarea
                  rows={2}
                  value={planForm.description}
                  onChange={(e) => setPlanForm({ ...planForm, description: e.target.value })}
                  placeholder="Summary of engineering scope and objective..."
                  className="w-full px-3 py-1.5 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              {/* Mandatory Safety Guidelines */}
              <div className="p-3 bg-amber-50/70 rounded-xl border border-amber-200">
                <label className="font-bold text-amber-900 block mb-1">
                  Mandatory Safety, LOTO (Lockout/Tagout) & PPE Instructions
                </label>
                <input
                  type="text"
                  value={planForm.safetyNotes}
                  onChange={(e) => setPlanForm({ ...planForm, safetyNotes: e.target.value })}
                  placeholder="e.g. LOCKOUT / TAGOUT mandatory before inspecting mechanical enclosures. Wear eye protection."
                  className="w-full px-3 py-1.5 border border-amber-300 rounded-lg text-xs bg-white focus:outline-none focus:ring-1 focus:ring-amber-500"
                />
              </div>

              {/* Checklist Task Items Builder */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="font-bold text-slate-800">Checklist Tasks & Evaluation Criteria</span>
                  <button
                    type="button"
                    onClick={() => {
                      setPlanForm({
                        ...planForm,
                        tasks: [
                          ...planForm.tasks,
                          {
                            id: `task-${Date.now().toString().slice(-4)}`,
                            order: planForm.tasks.length + 1,
                            task: '',
                            instruction: '',
                            type: 'pass_fail',
                            isRequired: true,
                          },
                        ],
                      });
                    }}
                    className="text-blue-600 font-bold hover:underline cursor-pointer"
                  >
                    + Add Task
                  </button>
                </div>

                <div className="space-y-2.5">
                  {planForm.tasks.map((t, idx) => (
                    <div key={idx} className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-2">
                      <div className="flex items-center gap-2">
                        <span className="w-5 h-5 rounded bg-slate-200 font-bold flex items-center justify-center shrink-0">
                          {idx + 1}
                        </span>
                        <input
                          type="text"
                          required
                          placeholder="Task title (e.g. Verify Spindle Radial Runout)"
                          value={t.task}
                          onChange={(e) => {
                            const val = e.target.value;
                            setPlanForm({
                              ...planForm,
                              tasks: planForm.tasks.map((task, i) => (i === idx ? { ...task, task: val } : task)),
                            });
                          }}
                          className="flex-1 px-2.5 py-1 bg-white border border-slate-300 rounded font-semibold focus:outline-none"
                        />
                        <select
                          value={t.type}
                          onChange={(e: any) => {
                            const val = e.target.value;
                            setPlanForm({
                              ...planForm,
                              tasks: planForm.tasks.map((task, i) => (i === idx ? { ...task, type: val } : task)),
                            });
                          }}
                          className="px-2 py-1 bg-white border border-slate-300 rounded font-medium focus:outline-none"
                        >
                          <option value="pass_fail">Pass / Fail</option>
                          <option value="numeric">Numeric Range</option>
                          <option value="text">Text Observation</option>
                        </select>
                        <button
                          type="button"
                          onClick={() => {
                            setPlanForm({
                              ...planForm,
                              tasks: planForm.tasks.filter((_, i) => i !== idx),
                            });
                          }}
                          className="text-slate-400 hover:text-rose-500 p-1 cursor-pointer"
                        >
                          ✕
                        </button>
                      </div>

                      {t.type === 'numeric' && (
                        <div className="flex items-center gap-2 pl-7">
                          <span className="text-slate-500">Min:</span>
                          <input
                            type="number"
                            step="any"
                            value={t.minValue ?? ''}
                            onChange={(e) => {
                              const num = e.target.value === '' ? undefined : parseFloat(e.target.value);
                              setPlanForm({
                                ...planForm,
                                tasks: planForm.tasks.map((task, i) => (i === idx ? { ...task, minValue: num } : task)),
                              });
                            }}
                            className="w-16 px-1.5 py-0.5 border border-slate-300 rounded text-center"
                          />
                          <span className="text-slate-500">Max:</span>
                          <input
                            type="number"
                            step="any"
                            value={t.maxValue ?? ''}
                            onChange={(e) => {
                              const num = e.target.value === '' ? undefined : parseFloat(e.target.value);
                              setPlanForm({
                                ...planForm,
                                tasks: planForm.tasks.map((task, i) => (i === idx ? { ...task, maxValue: num } : task)),
                              });
                            }}
                            className="w-16 px-1.5 py-0.5 border border-slate-300 rounded text-center"
                          />
                          <span className="text-slate-500">Unit:</span>
                          <input
                            type="text"
                            placeholder="e.g. MPa, bar, °C, µm"
                            value={t.unit ?? ''}
                            onChange={(e) => {
                              const u = e.target.value;
                              setPlanForm({
                                ...planForm,
                                tasks: planForm.tasks.map((task, i) => (i === idx ? { ...task, unit: u } : task)),
                              });
                            }}
                            className="w-24 px-2 py-0.5 border border-slate-300 rounded"
                          />
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Submit footer */}
              <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-200">
                <button
                  type="button"
                  onClick={() => setIsPlanModalOpen(false)}
                  className="px-4 py-2 font-semibold text-slate-600 hover:bg-slate-100 rounded-xl cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl shadow-xs cursor-pointer"
                >
                  {editingPlan ? 'Save Changes' : 'Create Master Plan'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* MODAL 4: SCHEDULE ASSIGNMENT MODAL */}
      {/* ========================================================================= */}
      {isScheduleModalOpen && (
        <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full p-6 border border-slate-200 animate-in fade-in zoom-in-95 duration-200 text-xs">
            <div className="flex items-center justify-between mb-4 pb-3 border-b border-slate-200">
              <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                <Calendar className="w-4 h-4 text-blue-600" />
                Assign Recurring PM Schedule
              </h2>
              <button
                onClick={() => setIsScheduleModalOpen(false)}
                className="text-slate-400 hover:text-slate-600 cursor-pointer"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleSaveSchedule} className="space-y-4">
              <div>
                <label className="font-bold text-slate-700 block mb-1">Target Machine / Asset *</label>
                <select
                  required
                  value={scheduleForm.machineId}
                  onChange={(e) => setScheduleForm({ ...scheduleForm, machineId: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-300 rounded-xl bg-white font-bold text-slate-900 focus:outline-none"
                >
                  <option value="">Select Machine...</option>
                  {machines.map((m) => (
                    <option key={m.id} value={m.id}>
                      {m.name} ({m.machineCode})
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">Master PM Plan *</label>
                <select
                  required
                  value={scheduleForm.planId}
                  onChange={(e) => setScheduleForm({ ...scheduleForm, planId: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-300 rounded-xl bg-white font-bold text-slate-900 focus:outline-none"
                >
                  <option value="">Select Master Plan...</option>
                  {plans.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.title} ({p.code} - {p.category})
                    </option>
                  ))}
                </select>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-bold text-slate-700 block mb-1">Frequency</label>
                  <select
                    value={scheduleForm.frequencyType}
                    onChange={(e) => setScheduleForm({ ...scheduleForm, frequencyType: e.target.value })}
                    className="w-full px-2.5 py-2 border border-slate-300 rounded-xl bg-white font-medium"
                  >
                    <option value="daily">Daily</option>
                    <option value="weekly">Weekly</option>
                    <option value="biweekly">Bi-Weekly</option>
                    <option value="monthly">Monthly</option>
                    <option value="quarterly">Quarterly</option>
                    <option value="semi_annually">Semi-Annually</option>
                    <option value="annually">Annually</option>
                  </select>
                </div>

                <div>
                  <label className="font-bold text-slate-700 block mb-1">First Due Date</label>
                  <input
                    type="date"
                    required
                    value={scheduleForm.nextDueDate}
                    onChange={(e) => setScheduleForm({ ...scheduleForm, nextDueDate: e.target.value })}
                    className="w-full px-2.5 py-2 border border-slate-300 rounded-xl font-bold font-mono"
                  />
                </div>
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">Assigned Maintenance Technician</label>
                <select
                  value={scheduleForm.assignedEmployeeId}
                  onChange={(e) => setScheduleForm({ ...scheduleForm, assignedEmployeeId: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-300 rounded-xl bg-white font-medium"
                >
                  <option value="">Auto-route to Department Operator</option>
                  {employees.map((emp) => (
                    <option key={emp.id} value={emp.id}>
                      {emp.name} ({emp.employeeCode})
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">Schedule Calculation Logic</label>
                <select
                  value={scheduleForm.scheduleType}
                  onChange={(e) => setScheduleForm({ ...scheduleForm, scheduleType: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-300 rounded-xl bg-white font-medium"
                >
                  <option value="fixed_calendar">Fixed Calendar (Strict recurring dates)</option>
                  <option value="rolling_after_completion">Rolling (Calculated from actual completion date)</option>
                </select>
              </div>

              <div className="flex items-center justify-end gap-2.5 pt-4 border-t border-slate-200">
                <button
                  type="button"
                  onClick={() => setIsScheduleModalOpen(false)}
                  className="px-3.5 py-2 font-semibold text-slate-600 hover:bg-slate-100 rounded-xl cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl shadow-xs cursor-pointer"
                >
                  Assign Schedule
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
